### ISSUE TITLE
use PostgresSaver Err

### ISSUE THREAD

**Issue by asynchat** [CopilotKit/sdk-python#3]
# use PostgresSaver

```
   |   File ".venv/lib/python3.11/site-packages/copilotkit/langgraph_agent.py", line 251, in _stream_events
...
...
    |     saved = await self.checkpointer.aget_tuple(self.checkpoint_config)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File ".venv/lib/python3.11/site-packages/langgraph/checkpoint/base/__init__.py", line 344, in aget_tuple
    |     raise NotImplementedError
    | NotImplementedError
    +------------------------------------
```

# use AsyncPostgresSaver

```
Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/copilotkit/integrations/fastapi.py", line 142, in handle_execute_agent
    events = sdk.execute_agent(
             ^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/copilotkit/sdk.py", line 167, in execute_agent
    raise AgentExecutionException(name, error) from error
copilotkit.exc.AgentExecutionException: Agent 'pro-table' failed to execute: Synchronous calls to AsyncPostgresSaver are only allowed from a different thread. From the main thread, use the async interface.For example, use `await checkpointer.aget_tuple(...)` or `await graph.ainvoke(...)`.
```

**Comment by RafaelChicovis** [comment]
I'm experiencing the same issue. Has there been any update on this?"
